# Generated by Django 3.2.9 on 2021-11-07 02:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 7, 2, 34, 25, 993133, tzinfo=utc), editable=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 7, 2, 34, 25, 992483, tzinfo=utc), editable=False),
        ),
    ]
